openapi: "3.0.3"

info:
  title: API Title
  version: "1.0"

servers:
  - url: http://127.0.0.1:54321/functions/v1

paths:
  /hello-world:
    post:
      operationId: "helloWorld"
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/helloWorldRequest"
      responses:
        200:
          $ref: "#/components/responses/helloWorldResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  requestBodies:
    helloWorldRequest:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
  responses:
    helloWorldResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
