create table "public"."author" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "sex" smallint,
    "birthday" date,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."author" enable row level security;

create table "public"."book" (
    "id" bigint generated by default as identity not null,
    "title" character varying not null,
    "category_code" bigint not null,
    "publisher" character varying not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."book" enable row level security;

create table "public"."book_author" (
    "id" bigint generated by default as identity not null,
    "book_id" bigint not null,
    "author_id" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
);


alter table "public"."book_author" enable row level security;

create table "public"."book_category" (
    "code" bigint not null,
    "name" character varying not null
);


alter table "public"."book_category" enable row level security;

CREATE UNIQUE INDEX author_pkey ON public.author USING btree (id);

CREATE UNIQUE INDEX book_author_pkey ON public.book_author USING btree (id);

CREATE UNIQUE INDEX book_category_pkey ON public.book_category USING btree (code);

CREATE UNIQUE INDEX book_pkey ON public.book USING btree (id);

alter table "public"."author" add constraint "author_pkey" PRIMARY KEY using index "author_pkey";

alter table "public"."book" add constraint "book_pkey" PRIMARY KEY using index "book_pkey";

alter table "public"."book_author" add constraint "book_author_pkey" PRIMARY KEY using index "book_author_pkey";

alter table "public"."book_category" add constraint "book_category_pkey" PRIMARY KEY using index "book_category_pkey";

alter table "public"."book" add constraint "book_category_code_fkey" FOREIGN KEY (category_code) REFERENCES book_category(code) not valid;

alter table "public"."book" validate constraint "book_category_code_fkey";

alter table "public"."book_author" add constraint "book_author_author_id_fkey" FOREIGN KEY (author_id) REFERENCES author(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."book_author" validate constraint "book_author_author_id_fkey";

alter table "public"."book_author" add constraint "book_author_book_id_fkey" FOREIGN KEY (book_id) REFERENCES book(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."book_author" validate constraint "book_author_book_id_fkey";

grant delete on table "public"."author" to "anon";

grant insert on table "public"."author" to "anon";

grant references on table "public"."author" to "anon";

grant select on table "public"."author" to "anon";

grant trigger on table "public"."author" to "anon";

grant truncate on table "public"."author" to "anon";

grant update on table "public"."author" to "anon";

grant delete on table "public"."author" to "authenticated";

grant insert on table "public"."author" to "authenticated";

grant references on table "public"."author" to "authenticated";

grant select on table "public"."author" to "authenticated";

grant trigger on table "public"."author" to "authenticated";

grant truncate on table "public"."author" to "authenticated";

grant update on table "public"."author" to "authenticated";

grant delete on table "public"."author" to "service_role";

grant insert on table "public"."author" to "service_role";

grant references on table "public"."author" to "service_role";

grant select on table "public"."author" to "service_role";

grant trigger on table "public"."author" to "service_role";

grant truncate on table "public"."author" to "service_role";

grant update on table "public"."author" to "service_role";

grant delete on table "public"."book" to "anon";

grant insert on table "public"."book" to "anon";

grant references on table "public"."book" to "anon";

grant select on table "public"."book" to "anon";

grant trigger on table "public"."book" to "anon";

grant truncate on table "public"."book" to "anon";

grant update on table "public"."book" to "anon";

grant delete on table "public"."book" to "authenticated";

grant insert on table "public"."book" to "authenticated";

grant references on table "public"."book" to "authenticated";

grant select on table "public"."book" to "authenticated";

grant trigger on table "public"."book" to "authenticated";

grant truncate on table "public"."book" to "authenticated";

grant update on table "public"."book" to "authenticated";

grant delete on table "public"."book" to "service_role";

grant insert on table "public"."book" to "service_role";

grant references on table "public"."book" to "service_role";

grant select on table "public"."book" to "service_role";

grant trigger on table "public"."book" to "service_role";

grant truncate on table "public"."book" to "service_role";

grant update on table "public"."book" to "service_role";

grant delete on table "public"."book_author" to "anon";

grant insert on table "public"."book_author" to "anon";

grant references on table "public"."book_author" to "anon";

grant select on table "public"."book_author" to "anon";

grant trigger on table "public"."book_author" to "anon";

grant truncate on table "public"."book_author" to "anon";

grant update on table "public"."book_author" to "anon";

grant delete on table "public"."book_author" to "authenticated";

grant insert on table "public"."book_author" to "authenticated";

grant references on table "public"."book_author" to "authenticated";

grant select on table "public"."book_author" to "authenticated";

grant trigger on table "public"."book_author" to "authenticated";

grant truncate on table "public"."book_author" to "authenticated";

grant update on table "public"."book_author" to "authenticated";

grant delete on table "public"."book_author" to "service_role";

grant insert on table "public"."book_author" to "service_role";

grant references on table "public"."book_author" to "service_role";

grant select on table "public"."book_author" to "service_role";

grant trigger on table "public"."book_author" to "service_role";

grant truncate on table "public"."book_author" to "service_role";

grant update on table "public"."book_author" to "service_role";

grant delete on table "public"."book_category" to "anon";

grant insert on table "public"."book_category" to "anon";

grant references on table "public"."book_category" to "anon";

grant select on table "public"."book_category" to "anon";

grant trigger on table "public"."book_category" to "anon";

grant truncate on table "public"."book_category" to "anon";

grant update on table "public"."book_category" to "anon";

grant delete on table "public"."book_category" to "authenticated";

grant insert on table "public"."book_category" to "authenticated";

grant references on table "public"."book_category" to "authenticated";

grant select on table "public"."book_category" to "authenticated";

grant trigger on table "public"."book_category" to "authenticated";

grant truncate on table "public"."book_category" to "authenticated";

grant update on table "public"."book_category" to "authenticated";

grant delete on table "public"."book_category" to "service_role";

grant insert on table "public"."book_category" to "service_role";

grant references on table "public"."book_category" to "service_role";

grant select on table "public"."book_category" to "service_role";

grant trigger on table "public"."book_category" to "service_role";

grant truncate on table "public"."book_category" to "service_role";

grant update on table "public"."book_category" to "service_role";


